SE-3550 [LX-1623] Ignore missing children in composite blocks
open-craft/labxchange-xblocks pull request #15
Opened 2020-12-23 05:03 UTC by swalladge

In the case where a child's xblock data was deleted,
we need to gracefully ignore it.

**Test instructions**:

- For each composite xblock (pathway, case study, assignment), delete a child xblock data, and load all the endpoints (including student_view) for the composite xblock.
- verify that the deleted children are not displayed, and that no errors are thrown.

See https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1214 for more information

**Reviewers**:

-  [ ] @symbolist

2021-01-05 21:31 UTC, symbolist requested changes

2021-01-05 21:31 UTC, symbolist commented on labxchange_xblocks/assignment_block.py
> +            except Exception:
A broad `Exception` catcher will end up hiding issues (and exception traces) due to other reasons. Can we only catch the specific exception that is raised in case the child xblock has been been deleted?

https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/xblock/runtime/blockstore_runtime.py#L36

2021-01-05 21:33 UTC, symbolist commented on labxchange_xblocks/assignment_block.py
> +                child_block = self.runtime.get_block(child_usage_id)
Can you please also add a test to cover the case where a child xblock is missing?

2021-01-06 01:24 UTC, swalladge commented on labxchange_xblocks/assignment_block.py
> +                child_block = self.runtime.get_block(child_usage_id)
I'm not sure a test will be meaningful, since the runtime is mocked in this repo... Will try though.

2021-01-06 22:27 UTC, symbolist commented on labxchange_xblocks/assignment_block.py
> +                child_block = self.runtime.get_block(child_usage_id)
For a specific usage_id, can raise an error in the mock and then see that `block_view_data()` continues to return the others: https://github.com/open-craft/labxchange-xblocks/blob/a08dcc18c8d3291f316ed4bd77862843bc406fb7/labxchange_xblocks/tests/assignment_block_test.py#L50

It is kind of like a frontend unit test where we pass in mock responses and check that the logic works as expected for such responses.

2021-01-07 00:47 UTC, swalladge commented on labxchange_xblocks/assignment_block.py
> +                child_block = self.runtime.get_block(child_usage_id)
Ah true, I'll do that, thanks. :)

2021-01-07 00:50 UTC, swalladge commented
@symbolist changes done as requested; ready for another review pass. :)

2021-03-18 22:49 UTC, s0b0lev commented
Hey @swalladge, I create a PR in the scope of FAL-1496. It solves the same issue. I take your tests from this PR, because they fit new PR quite well :sweat_smile:

2021-03-18 22:57 UTC, swalladge commented
Thanks @s0b0lev , closing as duplicate of #17 

Note that #17 covers this use case too, because https://github.com/edx/edx-platform/pull/27068 will coerce all errors to the new xblock parse exception.

2021-03-18 22:57 UTC, closed without merging