FAL-1496: Catch XBlockParseException for child items
open-craft/labxchange-xblocks pull request #17
Opened 2021-03-18 21:49 UTC by s0b0lev

Catch xblock parsing exception while read gets child blocks. If the child block fails to parse - we still will be able to update it via parent OLX code.

Deployment requirements:
- https://github.com/edx/XBlock/pull/516
- https://github.com/edx/edx-platform/pull/27068

Reviewers:
- @eLRuLL

2021-03-20 02:03 UTC, eLRuLL requested changes

2021-03-20 02:03 UTC, eLRuLL commented on labxchange_xblocks/tests/assignment_block_test.py
> +        })
@s0b0lev missing newline

2021-03-20 02:03 UTC, eLRuLL commented on labxchange_xblocks/tests/audio_block_test.py
> +        print(fragment.content)
@s0b0lev please remove this

2021-03-20 02:03 UTC, eLRuLL commented on labxchange_xblocks/tests/audio_block_test.py
> -    <div class="audio-block-transcript-student-view">
@s0b0lev why do these need to be removed?

2021-03-20 02:03 UTC, eLRuLL commented on labxchange_xblocks/tests/case_study_block_test.py
> +
empty line

2021-03-20 02:03 UTC, eLRuLL commented on labxchange_xblocks/tests/document_block_test.py
> +# E   + 	<object aria-label="Document" data="" type="application/pdf">
@s0b0lev is this necessary?

2021-03-20 11:09 UTC, s0b0lev commented on labxchange_xblocks/tests/audio_block_test.py
> -    <div class="audio-block-transcript-student-view">
8 tests for this package fails. Looks like implementation was updated without updating tests. 

I didn't touch any xblock internals, I only update tests to work with the current output (assuming that it is correct because we use this package on production).

2021-03-20 11:10 UTC, s0b0lev commented on labxchange_xblocks/tests/case_study_block_test.py
> +
Thanks, would be great to setup CI with linter/tests for this repo.

2021-03-20 16:38 UTC, eLRuLL approved these changes
@s0b0lev it looks good now :+1: ready to be merged

2021-03-20 17:21 UTC, s0b0lev commented
Thanks, @eLRuLL, I will merge it as soon as XBlock PR would be merged and the new version of xblock is published.

2021-04-04 19:58 UTC, symbolist requested changes

2021-04-04 19:58 UTC, symbolist commented on labxchange_xblocks/assignment_block.py
> +            except XBlockParseException:
Let's make this an `Exception` so that whatever the issue it is caught here. Can you log the exceptions being caught in this PR too so that we know what the issue is in each case?

2021-04-04 19:58 UTC, symbolist commented on labxchange_xblocks/tests/case_study_block_test.py
> +                return None
You can also add another child block for which instead of a `return` there is a `raise Exception` which will catch the test the exception catching being added in this PR.

2021-06-17 17:40 UTC, symbolist commented on labxchange_xblocks/utils.py
> +                    log.exception('Xblock child parsing error')
Since we are catching a broad `Exception` this could also be because of some other error. So we can make the error message generic like "Error getting child of XBlock with {child_usage_id}."

2021-06-17 17:41 UTC, symbolist commented
We have also added the TeachingGuide and VideoAnnotation XBlocks recently so will need to catch errors for those too.

2021-08-11 05:23 UTC, swalladge commented
rebased on master and addressed conflicts

2021-08-25 07:02 UTC, swalladge commented
Closing because the effort/reward ratio is too high. See [LX-1854](https://tasks.opencraft.com/browse/LX-1854) for discussion.

2021-08-25 07:02 UTC, closed without merging