Draft: [FAL-1847] [LX-1930] Annotated videos 0.1
open-craft/labxchange-xblocks pull request #18
Opened 2021-05-17 01:38 UTC by toxinu

This merge request is about adding the new xblock(s) for the annotated video.

**Jira tickets**

- [FAL-1847](https://tasks.opencraft.com/browse/FAL-1847)
- [LX-1930](https://tasks.opencraft.com/browse/LX-1930)

**Testing instructions**

TBA

**Reviewers**

- @symbolist

2021-05-27 21:08 UTC, symbolist requested changes
Can you also add Python unit tests for the new XBlock? Thanks!

2021-05-27 21:08 UTC, symbolist commented on labxchange_xblocks/annotated_video_block.py
> +            annotations.append({
Any reason to not copy the dictionary and then update `image_url` in it?

https://docs.python.org/3/library/copy.html#copy.copy

2021-05-27 23:48 UTC, toxinu commented on labxchange_xblocks/annotated_video_block.py
> +    def student_view_user_state(self, request, suffix=""):
@symbolist I decided to use `student_video_user_data` because I thought some of the user completion data will be served by this handler in the future. If this is the case, I guess that's the right handler name?

2021-05-28 00:09 UTC, toxinu commented on labxchange_xblocks/annotated_video_block.py
> +    annotations = List(help=_("Annotations"))
Done.

2021-05-28 00:09 UTC, toxinu commented on labxchange_xblocks/annotated_video_block.py
> +    video_id = String(help=_("Video ID"))
Done.

2021-05-28 00:09 UTC, toxinu commented on labxchange_xblocks/annotated_video_block.py
> +            annotations.append({
Updated, thanks. :)

2021-05-28 03:17 UTC, toxinu commented
> Can you also add Python unit tests for the new XBlock? Thanks!

Tests added. 👍

2021-05-30 20:22 UTC, symbolist commented on labxchange_xblocks/annotated_video_block.py
> +    def student_view_user_state(self, request, suffix=""):
Hmm, the convention is to use it just for user state so may we can make this `student_view_data_and_user_state()` to indicate it includes both?

2021-06-03 21:44 UTC, symbolist approved these changes
Can you also bump up the version number?

Once the handler name and package version number have updated. 👍🏽 

- [x] I tested this by creating annotated videos from the LX UI.
- [x] I read through the code
- [  I checked for accessibility issues
- [ ] Includes documentation

2021-06-07 01:56 UTC, toxinu commented on labxchange_xblocks/annotated_video_block.py
> +    def student_view_user_state(self, request, suffix=""):
@symbolist Updated, thanks for your advice.

2021-06-07 21:51 UTC, symbolist commented
@toxinu Great! Okay to proceed with merging. 🙂

2021-06-10 06:02 UTC, merged