FAL-2482 [LX-2242]
open-craft/labxchange-xblocks pull request #24
Opened 2021-10-19 04:52 UTC by swalladge

[FAL-2482](https://tasks.opencraft.com/browse/FAL-2482) | [LX-2242](https://tasks.opencraft.com/browse/LX-2242)

These changes are to support the transition from srt subtitles to inline html transcripts for audio blocks.

**Test instructions**:

- test as part of [opencraft/client/LabXchange/labxchange-dev!1532](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1532)
- read the code and verify the logic is correct and desirable

2021-10-21 03:45 UTC, swalladge commented on labxchange_xblocks/audio_block.py
> +            # this was throwing an error because couldn't save in LMS and/or without a draft
@symbolist @pomegranited will this be possible?  If we can convert them on the fly, and save them back to the xblock with the new format, we can quickly phase out and then drop support for srt files here.

2021-10-22 00:15 UTC, pomegranited commented on labxchange_xblocks/audio_block.py
> +            # this was throwing an error because couldn't save in LMS and/or without a draft
@swalladge Sure, (almost) anything's possible.. is that part of the scope of this ticket?  Also, does LX ever want Audio assets to sync with their transcripts? If so, then we need to keep the timestamps provided by SRT, so phasing them out may not be the best plan. Can you check with Tess on this?

But note: we don't want to drop support for importing SRT files, since that's the standard format that we can export from YouTube and other sources.

2021-10-22 01:00 UTC, swalladge commented on labxchange_xblocks/audio_block.py
> +            # this was throwing an error because couldn't save in LMS and/or without a draft
@pomegranited followed up on the ticket

2021-11-08 14:54 UTC, michaelbukachi approved these changes
@swalladge  :+1 looks good

- [x] I tested this: followed test instructions
- [x] I read through the code

2021-11-09 01:57 UTC, pomegranited requested changes

2021-11-09 01:57 UTC, pomegranited commented on labxchange_xblocks/audio_block.py
> +            # TODO: remove this legacy support once all audio blocks on prod have been updated.
@swalladge  Could you create an LX ticket for this work and reference its ID here? So we know when/where it's to be done.

2021-11-09 01:57 UTC, pomegranited commented on labxchange_xblocks/audio_block.py
> +            # TODO: remove this legacy support once all audio blocks on prod have been updated.
And please add a test for this logic -- ok to move to a separate method if that makes it easier to test.

2021-11-09 01:57 UTC, pomegranited commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
Could you add a test for a case where `transcripts` is not empty?

2021-11-09 22:41 UTC, swalladge commented on labxchange_xblocks/audio_block.py
> +            # TODO: remove this legacy support once all audio blocks on prod have been updated.
Created :) https://tasks.opencraft.com/browse/LX-2349

2021-11-09 22:46 UTC, swalladge commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
I can try.  Not sure whether to try mocking the block assets/files, or try testing just that logic.  It's all tied up together... :/

2021-11-10 00:14 UTC, swalladge commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
@pomegranited do you have advice for writing tests here?  I can't find any existing tests that work with assets to base off.

2021-11-10 03:53 UTC, pomegranited commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
How about the tests you added for [Case Study attachments](https://github.com/open-craft/labxchange-xblocks/blob/master/labxchange_xblocks/tests/case_study_block_test.py#L244)?

2021-11-15 00:11 UTC, swalladge commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
@pomegranited nah, case study attachments is just a simple [list field](https://github.com/open-craft/labxchange-xblocks/blob/9f4b7f05badfce562da43d9d8b1887ac81dc6298/labxchange_xblocks/case_study_block.py#L53-L58).

2021-11-15 00:45 UTC, swalladge commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
Working on it.  Will write custom mocks.

2021-11-15 00:57 UTC, swalladge commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
@pomegranited tests added! :)

2021-11-15 01:01 UTC, merged

2021-11-15 01:21 UTC, pomegranited commented on labxchange_xblocks/tests/audio_block_test.py
>                  'transcripts': {},
Looks great, thank you @swalladge !