FAL-2502 [LX-2287] Question block
open-craft/labxchange-xblocks pull request #25
Opened 2021-11-01 04:33 UTC by swalladge

[FAL-2502](https://tasks.opencraft.com/browse/FAL-2502) | [LX-2287](https://tasks.opencraft.com/browse/LX-2287)

WIP

2021-11-10 16:53 UTC, symbolist commented on labxchange_xblocks/question_block.py
> +    # - what is calculated elsewhere, vs calculated here, vs stored here?
* `has_score` is just a [constant](https://github.com/edx/edx-platform/blob/2d60224125211623676063184cf06dc47e4ca7bd/common/lib/xmodule/xmodule/capa_module.py#L156). It can be set to `True`.
* `weighted_possible` and `weighted_earned` are just [calculated](https://github.com/edx/edx-platform/blob/2d60224125211623676063184cf06dc47e4ca7bd/common/lib/xmodule/xmodule/capa_module.py#L888) on the fly. If the `weight` field is not being set, then it can be assumed to be 1 and we can keep the calculations simple.

2021-11-11 05:47 UTC, swalladge commented on Makefile
> +	python -m pytest -vvv -s --disable-pytest-warnings --ds=lms.envs.test --no-cov --nomigrations $(PROJECT_ROOT)labxchange_xblocks/tests/
This is simply a quality of life improvement - makes debugging failing tests a lot easier, and isn't any more verbose when tests are passing.

2021-11-15 09:42 UTC, toxinu approved these changes
Good to merge 👍

2021-11-16 18:51 UTC, symbolist requested changes

2021-11-16 18:51 UTC, symbolist commented on labxchange_xblocks/question_block.py
> +from xblockutils.studio_editable import StudioEditableXBlockMixin
Since [this](https://github.com/edx/xblock-utils) is AGPL3, we will need to remove it to be able to use this package in the backend. I do not think it should be needed anyway since we are not doing any edits in studio anymore. Originally this was added because the editors were not ready.

2021-11-16 18:51 UTC, symbolist commented on labxchange_xblocks/question_block.py
> +    # TODO: do we need to record timestamp of student attempts, or latest attempt?
Hmm, I do not think we have been tracking this. We mark the xblock as completed in the backend and that is used in the class progress report.

2021-11-16 18:51 UTC, symbolist commented on labxchange_xblocks/tests/question_block_test.py
> +Question block tests
Since this is not just a readonly XBlock and is quite complex, we will need more tests for it. Can you look at other XBlock packages and see how they are doing it? Some examples are:
1. https://github.com/edx/edx-ora2
2. https://github.com/edx-solutions/xblock-drag-and-drop-v2

2021-11-17 01:22 UTC, swalladge commented on labxchange_xblocks/question_block.py
> +            "hints": self.hints,
Yep this should be fine - these are the hints that are shown when the user clicks the 'hint' button.  The need to be always present for the user to view.

2021-11-17 01:55 UTC, swalladge commented on labxchange_xblocks/tests/question_block_test.py
> +Question block tests
Yep sure no worries.

2021-11-17 05:50 UTC, swalladge commented on labxchange_xblocks/tests/question_block_test.py
> +Question block tests
@symbolist I added a bunch of tests which results in about 98% coverage for question_block.py.  Also discovered some minor bugs, so this was a useful exercise in itself. Could you take another review pass now? :)

2021-11-17 16:15 UTC, symbolist approved these changes
Thanks for adding the comprehensive tests! Looks good to ship. 🚢

2021-11-17 21:36 UTC, merged