[FAL-2581] [LX-2360] New LXVideo xblock
open-craft/labxchange-xblocks pull request #27
Opened 2021-11-26 10:23 UTC by toxinu

This merge request is about adding a new LXVideo xblock.

**Jira tickets**

* [FAL-2581](https://tasks.opencraft.com/browse/FAL-2581)
* [LX-2360](https://tasks.opencraft.com/browse/LX-2360)

**Testing instructions**

TBA

**Reviewers**

* [ ] @swalladge

2021-11-28 22:56 UTC, swalladge commented on labxchange_xblocks/fields.py
> +    https://github.com/edx/edx-platform/blob/0cdaa91762b8af8612401fd768588a519e72cdcc/common/lib/xmodule/xmodule/fields.py
@toxinu unfortunately, we can't do this, because edx-platform is AGPL licensed, and this codebase is going to be merged into labxchange which is still closed source for now.

2021-11-28 22:59 UTC, swalladge commented on labxchange_xblocks/tests/video_block_test.py
> +
@toxinu where's that trailing newline gone? :thinking:

2021-11-28 23:13 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +        # TODO: Do we only have srt subtitles?
@toxinu yes, currently all subtitles are srt.  We will be adding support for inline html transcripts to videos too in the future, so the internal data structure will need to be extensible to add more types in the future.

2021-11-28 23:14 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +            add_attachment_header (bool): whether to add attachment header or not
@toxinu while you're here, these argument type annotations can be moved from the comments to actual annotations :wink:

2021-11-28 23:16 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +    )
@toxinu please make a note here about how the data is structured in this dictionary.  I'd suggest keys being the language code, and values being a dictionary with some kind of 'type' key so we can extend it with multiple content types later (srt file, inline srt, inline html, etc. - whatever we end up requiring).

2021-11-29 08:41 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +        # TODO: Do we only have srt subtitles?
@swalladge Great. It won't really be a problem for the block, most of the work will be handled by the frontend then.

2021-11-29 08:49 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +    )
@swalladge I wanted to keep the structure of the existing video block to be compatible and then we can change the block structure once we use this new block.

I think this is better to migrate and then change the structure later instead of doing it at the same time.

2021-11-29 09:10 UTC, toxinu commented on labxchange_xblocks/fields.py
> +    https://github.com/edx/edx-platform/blob/0cdaa91762b8af8612401fd768588a519e72cdcc/common/lib/xmodule/xmodule/fields.py
Still inspired but updated 👍

2021-11-29 09:24 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +    )
The structure of the internal fields doesn't matter; it just needs to be compatible with importing the old video OLX, and compatible with the old api endpoints.

2021-11-29 15:27 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +    )
@swalladge If the internal fields change, you can't import the old video OLXs as new ones. However, adding a new "type" along the filename can be done without any issue.

2021-11-29 15:37 UTC, toxinu commented
@swalladge I added a bunch of new tests.

2021-11-30 05:45 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +    }
@toxinu are we using JSON and TXT?

2021-11-30 05:50 UTC, swalladge commented
@toxinu is the video block supposed to remember your latest watch position?  For if you refresh the page halfway through?

2021-11-30 06:09 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +    student_view_template = "templates/video_student_view.html"
@toxinu we need to create a ticket to clean up and remove student_view related things, once we strip that out of labxchange and don't have any more blocks rendered through the student_view. :)

2021-11-30 06:10 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +        class FileObjForWebobFiles:  # pylint: disable=missing-class-docstring
@toxinu is there a reason this class needs to be embedded here?

2021-11-30 09:28 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +        class FileObjForWebobFiles:  # pylint: disable=missing-class-docstring
I don't think so. Deleting it 👍

2021-11-30 09:29 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +    }
The current video xblock supports these formats so I left them just in case. I am not sure if we have some assets using these.

2021-11-30 09:30 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +    student_view_template = "templates/video_student_view.html"
@swalladge Yes! It will be much more cleaner. :)

2021-11-30 19:41 UTC, symbolist requested changes
Hey, looking nice!

2021-12-01 08:58 UTC, toxinu commented on labxchange_xblocks/fields.py
> +            )
@symbolist Maybe but since we have ~4500 videos and some of these assets could have been imported from somewhere else, it is difficult to be sure.

2021-12-01 08:58 UTC, toxinu commented on labxchange_xblocks/fields.py
> +        If value is float (backward compatibility issue), convert to timedelta.
@symbolist I haven't checked the 4500 video assets we have so I can't say for sure.

2021-12-01 08:59 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +    transcript_language = fields.String(
@symbolist Yes it is.

2021-12-01 08:59 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +    show_captions = fields.Boolean(
The video player is saving this state so it might be.

2021-12-05 22:31 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +        default="Question",
@symbolist nah we don't use this field at all.  It's currently auto-set by labxchange.  We can drop these fields when we drop that from lx.

2021-12-08 21:33 UTC, swalladge commented on labxchange_xblocks/video_block.py
> +        print("!!!! 1", language, transcripts)
@toxinu don't forget to remove these debug prints before merge ;)

2021-12-08 21:51 UTC, swalladge approved these changes
@toxinu :+1:

- [x] I tested this: followed test instructions - tested with [opencraft/client/LabXchange/labxchange-dev!1574](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1574)
- [x] I read through the code and considered the security, stability and performance implications of the changes.
- [NA no ui changes] I tested that the UI can be used with a keyboard only (tab order, keyboard controls).
- [x] Includes tests for bugfixes and/or features added.
- [x] Includes documentation
- [x] Includes fixtures that create objects required for manual testing.

2021-12-09 09:15 UTC, toxinu commented on labxchange_xblocks/video_block.py
> +        print("!!!! 1", language, transcripts)
Removed. Thanks! :)

2021-12-09 09:18 UTC, merged

2021-12-09 09:21 UTC, toxinu commented
Merged and pinged on Slack: https://openedx.slack.com/archives/C01ATGRBBDM/p1639041680039300