[LX-2281] Adds BlockstoreService for when openedx is not available
open-craft/labxchange-xblocks pull request #31
Opened 2022-03-02 06:29 UTC by pomegranited

This PR allows these XBlocks to be run outside of Open edX by adding an optional "blockstore" service, which knows how to interact with the Blockstore/Content Libraries APIs to access the data that Open edX access directly.

The BlockstoreService itself is in the LabXchange code, but can be upstreamed if it's found to be broadly useful. (So far, no one else but LabXchange are using these XBlocks.)

**Testing instructions**

This branch is installed as part of [labxchange-dev#1632](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1632), so part of this change can be tested as part of that.

Additionally, please test that this branch works fine in the LMS/Studio by:

* Installing this branch in the lms and studio virtualenvs.
* Viewing audio and video XBlocks in LabXchange, and ensuring you can: watch the videos, read the transcripts, edit the metadata and OLX, and see the changes made.

**Reviewer**

- [ ] @giovannicimolin

2022-03-15 01:47 UTC, pomegranited commented
Oops, I meant to close https://github.com/open-craft/xblock-runtime-lib/pull/1, not this one.. 😬

2022-04-12 20:33 UTC, giovannicimolin commented on labxchange_xblocks/templatetags/i18n.py
> +"""
@pomegranited Why do we need this here? 
For LX blocks, we'll only use `student_view_data` and write directly to the OLX, no?

2022-04-12 20:41 UTC, giovannicimolin reviewed
~~Left a question about i18n code, but other than that it seems to be working as expected!~~ Scratch that, see my review below.

2022-04-12 21:15 UTC, giovannicimolin requested changes
@pomegranited 

This changes breaks `lx_image`, `lx_document`, and `lx_narrative` blocks because they rely on `submit_studio_edits` for saving changes, which comes from `StudioEditableXBlockMixin`. 
  - Code [here](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/blob/bb0b81bd9256f72671de29cb834cc56993398f86/backend/labxchange/apps/library/api/v1/block_editing.py#L99). 
  - Maybe there's an easy way out of this, depending on the complexity of what `submit_studio_edits` is doing?

2022-04-13 05:19 UTC, pomegranited commented on labxchange_xblocks/templatetags/i18n.py
> +"""
That's the goal, but we haven't gotten there yet. E.g., `html` blocks still render in LX using the `student_view` and the django templates, and questions (assignments) and the children of question sets (also assignments) are still rendered by edx-platform using `student_view` and templates. I'm not sure about the timing of fixing this, so figured it was better to support these views now.

I had [remove our dependency on the `ResourceLoader`](https://github.com/open-craft/labxchange-xblocks/pull/31/files/fb12aa9cbd0934b0157505ebc12b38f1955395f3#diff-67e5717ce1e8e6a125c6b5155d3df80a7e437ff2f963341b237ceb042d593b4dL10) because `xblockutils` is AGPL, and and that meant adding the [`_render_django_template`](https://github.com/open-craft/labxchange-xblocks/pull/31/files/fb12aa9cbd0934b0157505ebc12b38f1955395f3#diff-67e5717ce1e8e6a125c6b5155d3df80a7e437ff2f963341b237ceb042d593b4dR118) method below, which relies on this templatetag. Luckily, I contributed the `i18n1 templatetag ages back, so it was ok to pull in here.

2022-04-13 05:55 UTC, pomegranited commented
> This changes breaks `lx_image`, `lx_document`, and `lx_narrative` blocks because they rely on `submit_studio_edits` for saving changes, which comes from `StudioEditableXBlockMixin`.

Ach, good catch @giovannicimolin !  See https://github.com/open-craft/labxchange-xblocks/pull/31/commits/2029fb85f417810b4c52afe1dc8a0c593043eb41 -- I've maintained this dependency for when labxchange_xblocks is installed on the platform, since that's where the studio endpoints are called.  We'll need to rethink how to handle these field changes as part of our migration away from Open edX.

CC @symbolist

2022-04-13 06:08 UTC, pomegranited commented on labxchange_xblocks/templatetags/i18n.py
> +"""
As noted on the ticket, I can't use this code here since it wasn't written for LabXchange. So instead, I'll work on removing all dependencies on templates and student views from the LX code.

2022-04-23 19:15 UTC, pomegranited commented on labxchange_xblocks/templatetags/i18n.py
> +"""
@giovannicimolin  I've checked the templates for these XBlocks, and none of them actually use the `i18n` template tag. So I've removed that code from here, and we can proceed without converting everything to using `student_view_data` (yet).

Of course, ultimately, this is the goal, but it doesn't have to block this work.

2022-04-23 19:18 UTC, pomegranited commented on labxchange_xblocks/document_block.py
> +        """
@giovannicimolin to address [your previous comment](https://github.com/open-craft/labxchange-xblocks/pull/31#pullrequestreview-940155438):

> This changes breaks `lx_image`, `lx_document`, and `lx_narrative` blocks because they rely on `submit_studio_edits` for saving changes, which comes from StudioEditableXBlockMixin.
> 
>  * Code [here](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/blob/bb0b81bd9256f72671de29cb834cc56993398f86/backend/labxchange/apps/library/api/v1/block_editing.py#L99).
> * Maybe there's an easy way out of this, depending on the complexity of what `submit_studio_edits` is doing?

I've been testing this change on my devstack, and it doesn't seem to break editing for these block types? Plus, by using these `ImportError` handlers here, we can still run this code on LX and respect the AGPL boundaries. To explain:

When this branch is installed on edx-platform LMS/Studio:
1. it *does* have the `xblockutils` library installed, and so the `ImportError` clauses here do not get triggered, and the blocks inherit as expected from `xblockutils.studio_editable.StudioEditableXBlockMixin`.
1. the labxchange-xblocks served by LMS/Studio *do* have the `submit_studio_edits` handler, and so LabXchange can save changes to the OLX.

When this branch is installed on LabXchange:
1. It *doesn't* have the `xblockutils` library installed -- respecting the AGPL license -- and so the `ImportError` clauses here do get triggered.
1. the labxchange-xblocks served by LX *do not* have the `submit_studio_edits` handler, but they don't need it yet. We'll be rewriting the block save logic as part of another task.

Do you agree with the logic here?

2022-05-11 14:33 UTC, giovannicimolin commented on labxchange_xblocks/document_block.py
> +        """
@pomegranited It does make sense. Once this is merged, what would be the license of this code? Will this be a dual-licensed repo (`Apache` for LX backend and `AGPL` for Open edX when using the import)? 

I don't want to block this ticket on the license discussion, so I'll :+1: this as long as it works.
Whatever licensing approach we end up going for, we should get a :+1: from @symbolist too.

2022-05-11 18:05 UTC, giovannicimolin approved these changes
:+1: 

- [x] I tested this: tested alongside https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1632#d577c19e92846e56b56054059df2bc52084c11f8. :heavy_check_mark: 
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA
- [ ] Includes documentation: the LICENSE file here is still AGPL and needs to be updated depending on the outcome of the licensing discussion.

@pomegranited Great work here. This is conditionally approved on:

- Updating the repo's LICENSE file with the outcome of the discussion.
- Getting a :+1: from @symbolist on the License approach we end up choosing.

2022-05-12 01:13 UTC, pomegranited commented on labxchange_xblocks/document_block.py
> +        """
Ah. Excellent point @giovannicimolin !

I've pushed [1ea4767](https://github.com/open-craft/labxchange-xblocks/pull/31/commits/1ea476794c3746415230bc046c85466297a6643f) to change the license for this repo to Apache 2.0, which matches [openedx:XBlock's license](https://github.com/openedx/XBlock/blob/master/LICENSE.TXT). This is necessary in order to use this repo as a dependency in LabXchange.

This repo was developed entirely by OpenCraft for the LabXchange project, and so I think this is ok to do.. but would like a 👍 from @bradenmacdonald and @symbolist before merging. CC @antoviaque

2022-05-12 16:50 UTC, symbolist commented on labxchange_xblocks/document_block.py
> +        """
@giovannicimolin @pomegranited Sure, changing the license to Apache is fine.

2022-05-16 00:40 UTC, pomegranited commented on labxchange_xblocks/document_block.py
> +        """
@antoviaque This is only XBlocks developed for LabXchange specifically.

Thank you for clarifying, we'll go ahead with this change.

2022-05-16 01:15 UTC, merged