[LX-2537] Fixing question set children bugs
open-craft/labxchange-xblocks pull request #34
Opened 2022-05-20 19:37 UTC by ChrisChV

This merge request is to fix the question set children when the user is in migration testers group

Ticket: https://tasks.opencraft.com/browse/LX-2537

Testing instructions:

- Install this branch in your devstack
- Login wiht `edx` (In Django admin verify that `edx` is in MIGRATION_TESTEST)
- Go to this [question set](http://localhost:4556/library/items/lb:LabXchange:340d8e06:lx_assignment:1)
- Verify that the questions are all good

2022-05-23 08:55 UTC, pomegranited requested changes
Great find with this bug @ChrisChV ! Requested a change, but should be able to approve after that.

Could you also bump the version to `0.9.2` in labxchange_xblocks/__init__.py?

2022-05-23 08:55 UTC, pomegranited commented on labxchange_xblocks/assignment_block.py
> +            child_block = self.runtime.get_block(child_usage_id, block_type_overrides=LX_BLOCK_TYPES_OVERRIDE)
I think we need to do something similar for [case study blocks](https://github.com/open-craft/labxchange-xblocks/blob/997ac12e8ce5a29dbe4c22bc421c212c032d3efa/labxchange_xblocks/case_study_block.py#L96)?

So we should define `LX_BLOCK_TYPES_OVERRIDE` somewhere common to all our blocks, and include [all the overridden block types](https://github.com/openedx/edx-platform/blob/c04e63d271b502f95e555d34991ccb83af0fe271/openedx/core/djangoapps/xblock/rest_api/views.py#L32-L36).

2022-05-23 08:55 UTC, pomegranited commented on labxchange_xblocks/assignment_block.py
> +        if getattr(block, 'has_score', False) is True and getattr(block, 'get_score', None) is not None:
QuestionBlocks need to implement `get_score`  so that this change isn't required. This fix allows us to reflect correct scores for lx_questions and question blocks (something else that was missed in testing).

Should look something like:

```
from xblock.scorable import Score

def get_score(self):
    possible = self.weight if self.weight > 0 else 1
    correct = self._is_correct()
    earned = possible if correct else 0
    return Score(raw_earned=earned, raw_possible=possible)
```

2022-05-23 19:15 UTC, ChrisChV commented on labxchange_xblocks/assignment_block.py
> +            child_block = self.runtime.get_block(child_usage_id, block_type_overrides=LX_BLOCK_TYPES_OVERRIDE)
I added this change in all block that use get_block

2022-05-23 19:15 UTC, ChrisChV commented on labxchange_xblocks/assignment_block.py
> +        if getattr(block, 'has_score', False) is True and getattr(block, 'get_score', None) is not None:
Thanks! I added the function and some tests

2022-05-24 05:21 UTC, pomegranited approved these changes
:+1: Thanks for addressing my concerns, and for getting all of these pylint issues fixed too!

- [x] I tested this on my devstack using the PR test instructions. I made sure that scoring of question set children is working as expected, that question set and teaching guide/case study children are rendering as LX XBlocks, and that the [README#Testing instructions](https://github.com/open-craft/labxchange-xblocks#testing-on-devstack) pass.
- [x] I read through the code and considered the security, stability and performance implications of the changes.
- [x] <strike>I tested that the UI can be used with a keyboard only (tab order, keyboard controls).</strike> N/A - no UI changes
- [x] Includes tests for bugfixes and/or features added.
- [x] <strike>Includes documentation</strike> N/A

2022-05-24 05:36 UTC, pomegranited commented
@ChrisChV  I'm testing this with a non-MIGRATION_TESTER user, and child blocks inside of question sets, teaching guides, and case studies are _not_ rendering properly :( So we're going to have to time the release of this with the release of @giovannicimolin 's change to enable LX XBlocks for all users.

2022-06-01 05:14 UTC, merged